### ISSUE TITLE
How to use it ? 

### ISSUE THREAD

**Issue by Jakezheng** [PragmaticClub/ng2-qrcode#2]
I want to use it in my ionic2 project how do it use 
I am new to angular 2 
Thanks

**Comment by pragmatic-club** [comment]
Hello,
I made a quick [plunkr](http://plnkr.co/nimekIYZFgWy82B49pGu) to show you how it can be integrated in Ionic2...
Good luck ;-)

**Comment by Jakezheng** [comment]
Thank you ;)

**Comment by matejamateusz** [comment]
Hey, (un)fortunately ionic 2 now has changed - I cannot make it working with the ionic 2 rc1, can you please show how to do it? Thank you very much
